apiVersion: elasticscale.com.sjtu.cit/v1
kind: BackupDeployment
metadata:
  name: backupdeployment-sample
spec:
  # Add fields here
  serviceName:
    - "webapp-service"
  initalWait: 2000 #单位为豪秒
  action: waiting
  backupReplicas: 3
  runningReplicas: 1
  backupSpec:
    selector:
      matchLabels:
        app: webapp
    template:
      metadata:
        labels:
          app: webapp
      spec:
        containers:
          - name: webapp
            image: kubeguide/tomcat-app:v1
            ports:
              - containerPort: 8080
            resources:
              requests:
                memory: "30Mi"
                cpu: "10m"
              limits:
                memory: "30Mi"
                cpu: "10m"
  runningSpec:
    selector:
      matchLabels:
        app: webapp
    template:
      metadata:
        labels:
          app: webapp
      spec:
        containers:
          - name: webapp
            image: kubeguide/tomcat-app:v1
            ports:
              - containerPort: 8080
            resources:
              requests:
                memory: "1024Mi"
                cpu: "200m"
              limits:
                memory: "1024Mi"
                cpu: "200m"