# permissions for end users to edit elasticwebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticweb-editor-role
rules:
- apiGroups:
  - elasticweb.elastic.demo.io
  resources:
  - elasticwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticweb.elastic.demo.io
  resources:
  - elasticwebs/status
  verbs:
  - get
